package com.mel.bubblenotes.repositories

import com.mel.bubblenotes.models.Note
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import kotlinx.coroutines.runBlocking
import java.sql.Connection
import java.util.UUID
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class NoteRepositoryTest {

    private lateinit var dataSource: HikariDataSource
    private lateinit var noteRepository: NoteRepository

    fun setup() {
        // Setup H2 in-memory database
        val hikariConfig = HikariConfig().apply {
            jdbcUrl = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
            username = "sa"
            password = ""
        }
        dataSource = HikariDataSource(hikariConfig)
        
        // Create schema
        val connection = dataSource.connection
        createSchema(connection)
        
        noteRepository = NoteRepository(connection)
    }

    fun teardown() {
        dataSource.close()
    }

    @Test
    fun testCreateAndFindNote() = runBlocking {
        setup()
        try {
            val userId = UUID.randomUUID()
            val now = System.currentTimeMillis()
            
            // Create a note
            val note = Note(
                id = 0, // Will be generated by database
                userId = userId,
                title = "Test Note",
                content = "This is test content",
                isPublished = true,
                createdAt = now,
                updatedAt = now
            )

            val createdId = noteRepository.create(note)
            assertTrue(createdId > 0, "Created note should have a positive ID")

            // Find the note by ID
            val foundNote = noteRepository.findById(createdId)
            assertNotNull(foundNote, "Found note should not be null")
            assertEquals("Test Note", foundNote.title, "Title should match")
            assertEquals("This is test content", foundNote.content, "Content should match")
            assertEquals(userId, foundNote.userId, "User ID should match")
        } finally {
            teardown()
        }
    }

    @Test
    fun testUpdateNote() = runBlocking {
        setup()
        try {
            val userId = UUID.randomUUID()
            val now = System.currentTimeMillis()
            
            // Create a note first
            val note = Note(
                id = 0,
                userId = userId,
                title = "Original Title",
                content = "Original content",
                isPublished = true,
                createdAt = now,
                updatedAt = now
            )
            val createdId = noteRepository.create(note)

            // Update the note
            val updatedNote = Note(
                id = createdId,
                userId = userId,
                title = "Updated Title",
                content = "Updated content",
                isPublished = false,
                createdAt = now,
                updatedAt = System.currentTimeMillis()
            )
            
            val success = noteRepository.update(updatedNote)
            assertTrue(success, "Update should succeed")

            // Verify the update
            val foundNote = noteRepository.findById(createdId)
            assertNotNull(foundNote)
            assertEquals("Updated Title", foundNote.title)
            assertEquals("Updated content", foundNote.content)
            assertFalse(foundNote.isPublished)
        } finally {
            teardown()
        }
    }

    @Test
    fun testDeleteNote() = runBlocking {
        setup()
        try {
            val userId = UUID.randomUUID()
            val now = System.currentTimeMillis()
            
            // Create a note first
            val note = Note(
                id = 0,
                userId = userId,
                title = "To Delete",
                content = "Content to delete",
                isPublished = true,
                createdAt = now,
                updatedAt = now
            )
            val createdId = noteRepository.create(note)

            // Delete the note
            val success = noteRepository.delete(createdId, userId)
            assertTrue(success, "Delete should succeed")

            // Verify the note is deleted
            val foundNote = noteRepository.findById(createdId)
            assertEquals(null, foundNote, "Note should be deleted")
        } finally {
            teardown()
        }
    }

    @Test
    fun testFindByUserId() = runBlocking {
        setup()
        try {
            val userId = UUID.randomUUID()
            val otherUserId = UUID.randomUUID()
            val now = System.currentTimeMillis()
            
            // Create multiple notes for the same user
            repeat(3) { i ->
                val note = Note(
                    id = 0,
                    userId = userId,
                    title = "Note $i",
                    content = "Content $i",
                    isPublished = true,
                    createdAt = now + i,
                    updatedAt = now + i
                )
                noteRepository.create(note)
            }

            // Create a note for another user
            val otherNote = Note(
                id = 0,
                userId = otherUserId,
                title = "Other User's Note",
                content = "Should not appear",
                isPublished = true,
                createdAt = now,
                updatedAt = now
            )
            noteRepository.create(otherNote)

            // Find notes by user ID
            val notes = noteRepository.findByUserId(userId, limit = 10)
            assertEquals(3, notes.size, "Should find exactly 3 notes for the user")
            
            // Verify none of them belong to the other user
            notes.forEach { note ->
                assertEquals(userId, note.userId, "All notes should belong to the correct user")
            }
        } finally {
            teardown()
        }
    }

    @Test
    fun testCountByUserId() = runBlocking {
        setup()
        try {
            val userId = UUID.randomUUID()
            val now = System.currentTimeMillis()
            
            // Create multiple notes
            repeat(5) { i ->
                val note = Note(
                    id = 0,
                    userId = userId,
                    title = "Note $i",
                    content = "Content $i",
                    isPublished = true,
                    createdAt = now + i,
                    updatedAt = now + i
                )
                noteRepository.create(note)
            }

            // Count notes for the user
            val count = noteRepository.countByUserId(userId)
            assertEquals(5, count, "Should have 5 notes")
        } finally {
            teardown()
        }
    }

    @Test
    fun testNoteWithNullTitle() = runBlocking {
        setup()
        try {
            val userId = UUID.randomUUID()
            val now = System.currentTimeMillis()
            
            // Create a note with null title
            val note = Note(
                id = 0,
                userId = userId,
                title = null,
                content = "Content without title",
                isPublished = true,
                createdAt = now,
                updatedAt = now
            )

            val createdId = noteRepository.create(note)
            assertTrue(createdId > 0)

            val foundNote = noteRepository.findById(createdId)
            assertNotNull(foundNote)
            assertEquals(null, foundNote.title)
        } finally {
            teardown()
        }
    }

    // Helper function to create schema in H2 database
    private fun createSchema(connection: Connection) {
        connection.createStatement().use { stmt ->
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS notes (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    user_id UUID NOT NULL,
                    title VARCHAR(255),
                    content TEXT NOT NULL,
                    is_published BOOLEAN DEFAULT TRUE,
                    ai_title VARCHAR(255),
                    ai_summary TEXT,
                    ai_tags VARCHAR(4096),
                    last_version_id BIGINT,
                    created_at BIGINT NOT NULL,
                    updated_at BIGINT NOT NULL
                )
            """.trimIndent())

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS tags (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    user_id UUID NOT NULL,
                    name VARCHAR(100) NOT NULL,
                    created_at BIGINT NOT NULL
                )
            """.trimIndent())

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS attachments (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    note_id BIGINT NOT NULL,
                    user_id UUID NOT NULL,
                    file_name VARCHAR(255) NOT NULL,
                    content_type VARCHAR(100) NOT NULL,
                    file_size BIGINT NOT NULL,
                    storage_path VARCHAR(500),
                    encrypted_data BLOB,
                    created_at BIGINT NOT NULL
                )
            """.trimIndent())

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS versions (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    note_id BIGINT NOT NULL,
                    user_id UUID NOT NULL,
                    title VARCHAR(255),
                    content TEXT NOT NULL,
                    created_at BIGINT NOT NULL
                )
            """.trimIndent())

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id UUID PRIMARY KEY,
                    email VARCHAR(255) UNIQUE NOT NULL,
                    name VARCHAR(255),
                    avatar_url VARCHAR(500),
                    created_at BIGINT NOT NULL,
                    updated_at BIGINT NOT NULL
                )
            """.trimIndent())

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS api_keys (
                    id UUID PRIMARY KEY,
                    user_id UUID NOT NULL,
                    key_hash VARCHAR(64) NOT NULL UNIQUE,
                    name VARCHAR(100),
                    created_at BIGINT NOT NULL,
                    expires_at BIGINT
                )
            """.trimIndent())
        }
    }
}
