package com.mel.bubblenotes.api

import com.mel.bubblenotes.UserId
import com.mel.bubblenotes.UserSession
import com.mel.bubblenotes.getInjector
import com.mel.bubblenotes.models.Note
import com.mel.bubblenotes.repositories.NoteRepository
import com.mel.bubblenotes.repositories.UserRepository
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.sessions.*
import java.util.UUID

data class NoteCreationRequest(val title: String?, val content: String)
data class NoteUpdateRequest(val title: String?, val content: String?, val isPublished: Boolean?)

// NoteRepository instance - should be injected via dependency injection in production
var noteRepository: NoteRepository? = null

fun Route.notesApi() {
    // Protected routes - require authentication via session cookie
    authenticate("session-auth") {
        route("/api/v1/notes") {
        // Create a new note
        post {
            val noteData = call.receive<NoteCreationRequest>()
            val repo = noteRepository ?: return@post call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            
            // Get userId from authenticated principal
            val userId = UUID.fromString(call.principal<UserId>()?.id ?: return@post call.respond(HttpStatusCode.Unauthorized, mapOf("error" to "Not authenticated")))
            
            // Validate that the user exists in the database
            val userRepository = try {
                call.application.getInjector().getInstance(UserRepository::class.java)
            } catch (e: Exception) {
                null
            }
            if (userRepository != null) {
                val user = userRepository.findById(userId)
                if (user == null) {
                    // User not found - session is invalid, clear it if possible
                    call.application.log.error("User $userId not found in database - session may be stale")
                    try {
                        call.sessions.clear<UserSession>()
                    } catch (e: Exception) {
                        // Session clear failed, but we still return unauthorized
                        call.application.log.warn("Failed to clear session: ${e.message}")
                    }
                    return@post call.respond(HttpStatusCode.Unauthorized, mapOf("error" to "Session expired, please login again"))
                }
            }
            
            val note = Note(
                id = 0, // Will be generated by database
                userId = userId,
                title = noteData.title?.takeIf { it.isNotBlank() },
                content = noteData.content,
                isPublished = true,
                createdAt = System.currentTimeMillis(),
                updatedAt = System.currentTimeMillis()
            )
            
            val createdId = repo.create(note)
            call.respond(HttpStatusCode.Created, mapOf("id" to createdId))
        }
        
        // Get all notes for current user
        get {
            val limit = call.request.queryParameters["limit"]?.toIntOrNull() ?: 20
            val cursor = call.request.queryParameters["cursor"]?.toLongOrNull()
            
            val repo = noteRepository ?: return@get call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            // Get userId from authenticated principal
            val userId = UUID.fromString(call.principal<UserId>()?.id ?: return@get call.respond(HttpStatusCode.Unauthorized, mapOf("error" to "Not authenticated")))
            val notes = repo.findByUserId(userId, limit, cursor)
            
            call.respond(HttpStatusCode.OK, notes)
        }
        
        // Get a specific note
        get("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@get call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid note ID"))
            
            val repo = noteRepository ?: return@get call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            val note = repo.findById(id)
            
            if (note != null) {
                call.respond(HttpStatusCode.OK, note)
            } else {
                call.respond(HttpStatusCode.NotFound, mapOf("error" to "Note not found"))
            }
        }
        
        // Update a note
        put("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@put call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid note ID"))
            val noteData = call.receive<NoteUpdateRequest>()
            
            val repo = noteRepository ?: return@put call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            val userId = UUID.randomUUID() // In production, get from authenticated user
            
            val existingNote = repo.findById(id) ?: return@put call.respond(HttpStatusCode.NotFound, mapOf("error" to "Note not found"))
            
            val updatedNote = existingNote.copy(
                title = noteData.title?.takeIf { it.isNotBlank() } ?: existingNote.title,
                content = noteData.content ?: existingNote.content,
                isPublished = noteData.isPublished ?: existingNote.isPublished,
                updatedAt = System.currentTimeMillis()
            )
            
            if (repo.update(updatedNote)) {
                call.respond(HttpStatusCode.OK, updatedNote)
            } else {
                call.respond(HttpStatusCode.NotFound, mapOf("error" to "Failed to update note"))
            }
        }
        
        // Delete a note
        route("/{id}") {
            delete {
                val id = call.parameters["id"]?.toLongOrNull() ?: return@delete call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid note ID"))
                
                val repo = noteRepository ?: return@delete call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
                val userId = UUID.fromString(call.principal<UserId>()?.id ?: return@delete call.respond(HttpStatusCode.Unauthorized, mapOf("error" to "Not authenticated")))
                
                if (repo.delete(id, userId)) {
                    call.respond(HttpStatusCode.NoContent)
                } else {
                    call.respond(HttpStatusCode.NotFound, mapOf("error" to "Note not found"))
                }
            }
        }
    }
    }
}
