package com.mel.bubblenotes.api

import com.mel.bubblenotes.models.Note
import com.mel.bubblenotes.repositories.NoteRepository
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import java.util.UUID

data class NoteCreationRequest(val title: String?, val content: String)
data class NoteUpdateRequest(val title: String?, val content: String?, val isPublished: Boolean?)

// NoteRepository instance - should be injected via dependency injection in production
var noteRepository: NoteRepository? = null

fun Route.notesApi() {
    route("/api/v1/notes") {
        // Create a new note
        post {
            val noteData = call.receive<NoteCreationRequest>()
            val repo = noteRepository ?: return@post call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            
            val userId = UUID.randomUUID() // In production, get from authenticated user
            val note = Note(
                id = 0, // Will be generated by database
                userId = userId,
                title = noteData.title?.takeIf { it.isNotBlank() },
                content = noteData.content,
                isPublished = true,
                createdAt = System.currentTimeMillis(),
                updatedAt = System.currentTimeMillis()
            )
            
            val createdId = repo.create(note)
            call.respond(HttpStatusCode.Created, mapOf("id" to createdId))
        }
        
        // Get all notes for current user
        get {
            val limit = call.request.queryParameters["limit"]?.toIntOrNull() ?: 20
            val cursor = call.request.queryParameters["cursor"]?.toLongOrNull()
            
            val repo = noteRepository ?: return@get call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            val userId = UUID.randomUUID() // In production, get from authenticated user
            val notes = repo.findByUserId(userId, limit, cursor)
            
            call.respond(HttpStatusCode.OK, notes)
        }
        
        // Get a specific note
        get("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@get call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid note ID"))
            
            val repo = noteRepository ?: return@get call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            val note = repo.findById(id)
            
            if (note != null) {
                call.respond(HttpStatusCode.OK, note)
            } else {
                call.respond(HttpStatusCode.NotFound, mapOf("error" to "Note not found"))
            }
        }
        
        // Update a note
        put("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@put call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid note ID"))
            val noteData = call.receive<NoteUpdateRequest>()
            
            val repo = noteRepository ?: return@put call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            val userId = UUID.randomUUID() // In production, get from authenticated user
            
            val existingNote = repo.findById(id) ?: return@put call.respond(HttpStatusCode.NotFound, mapOf("error" to "Note not found"))
            
            val updatedNote = existingNote.copy(
                title = noteData.title?.takeIf { it.isNotBlank() } ?: existingNote.title,
                content = noteData.content ?: existingNote.content,
                isPublished = noteData.isPublished ?: existingNote.isPublished,
                updatedAt = System.currentTimeMillis()
            )
            
            if (repo.update(updatedNote)) {
                call.respond(HttpStatusCode.OK, updatedNote)
            } else {
                call.respond(HttpStatusCode.NotFound, mapOf("error" to "Failed to update note"))
            }
        }
        
        // Delete a note
        delete("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@delete call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid note ID"))
            
            val repo = noteRepository ?: return@delete call.respond(HttpStatusCode.ServiceUnavailable, mapOf("error" to "Database not configured"))
            val userId = UUID.randomUUID() // In production, get from authenticated user
            
            if (repo.delete(id, userId)) {
                call.respond(HttpStatusCode.NoContent)
            } else {
                call.respond(HttpStatusCode.NotFound, mapOf("error" to "Note not found"))
            }
        }
    }
}
