package com.mel.bubblenotes.api

import com.mel.bubblenotes.models.Note
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import java.util.UUID

data class NoteCreationRequest(val title: String?, val content: String)
data class NoteUpdateRequest(val title: String?, val content: String?, val isPublished: Boolean?)

fun Route.notesApi() {
    route("/api/v1/notes") {
        // Create a new note
        post {
            val noteData = call.receive<NoteCreationRequest>()
            
            val note = Note(
                id = 0, // Will be generated by database
                userId = UUID.randomUUID(),
                title = noteData.title?.takeIf { it.isNotBlank() },
                content = noteData.content,
                isPublished = true,
                createdAt = System.currentTimeMillis(),
                updatedAt = System.currentTimeMillis()
            )
            
            call.respond(HttpStatusCode.Created, mapOf("id" to 1L))
        }
        
        // Get all notes for current user
        get {
            val limit = call.request.queryParameters["limit"]?.toIntOrNull() ?: 20
            val cursor = call.request.queryParameters["cursor"]?.toLongOrNull()
            
            call.respond(HttpStatusCode.OK, listOf<Note>())
        }
        
        // Get a specific note
        get("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@get call.respond(HttpStatusCode.BadRequest)
            
            call.respond(HttpStatusCode.NotFound)
        }
        
        // Update a note
        put("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@put call.respond(HttpStatusCode.BadRequest)
            val noteData = call.receive<NoteUpdateRequest>()
            
            call.respond(HttpStatusCode.NotFound)
        }
        
        // Delete a note
        delete("/{id}") {
            val id = call.parameters["id"]?.toLongOrNull() ?: return@delete call.respond(HttpStatusCode.BadRequest)
            
            call.respond(HttpStatusCode.NoContent)
        }
    }
}
