-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    given_name VARCHAR(100),
    family_name VARCHAR(100),
    picture_url CLOB,
    oauth_token VARBINARY NOT NULL,
    encryption_salt CHAR(32) NOT NULL,
    api_key VARCHAR(64) UNIQUE NOT NULL,
    created_at BIGINT DEFAULT 0,
    updated_at BIGINT DEFAULT 0
);

-- Tags table
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    name VARCHAR(50) NOT NULL,
    created_at BIGINT DEFAULT 0,
    UNIQUE(user_id, name)
);

-- Notes table
CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    title CLOB,
    content CLOB NOT NULL,
    is_published BOOLEAN DEFAULT TRUE,
    ai_title VARCHAR(255),
    ai_summary CLOB,
    ai_tags CLOB,
    last_version_id BIGINT,
    preview_data CLOB,
    tags CLOB DEFAULT '[]',
    search_vector TEXT,
    created_at BIGINT DEFAULT 0,
    updated_at BIGINT DEFAULT 0
);

-- Version table
CREATE TABLE versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    title CLOB NOT NULL,
    content CLOB NOT NULL,
    tags CLOB NOT NULL,
    created_by UUID NOT NULL REFERENCES users(id),
    created_at BIGINT DEFAULT 0
);

-- NoteTag join table
CREATE TABLE note_tags (
    note_id BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id),
    user_id UUID NOT NULL REFERENCES users(id),
    PRIMARY KEY (note_id, tag_id),
    CONSTRAINT note_tags_unique UNIQUE (note_id, tag_id, user_id)
);

-- Attachments table
CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id),
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path CLOB NOT NULL,
    encrypted_data VARBINARY,
    created_at BIGINT DEFAULT 0
);

-- API Tokens table
CREATE TABLE api_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    token_hash CHAR(64) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    last_used_at BIGINT,
    created_at BIGINT DEFAULT 0
);

-- AI Tasks table
CREATE TABLE ai_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'pending',
    result CLOB,
    error_message CLOB,
    started_at BIGINT,
    completed_at BIGINT,
    worker_id VARCHAR(100),
    locked_at BIGINT,
    lock_timeout BIGINT DEFAULT 300000
);

-- Index for stale lock detection
CREATE INDEX idx_ai_tasks_status_locked_at ON ai_tasks (status, locked_at);

-- Index for worker_id lookups
CREATE INDEX idx_ai_tasks_worker_id ON ai_tasks (worker_id);

-- Index for full-text search on notes.search_vector
-- PostgreSQL: Uses GIN index for tsvector/full-text search
-- H2: Uses standard B-tree index (GIN is not supported, will use default)
CREATE INDEX idx_notes_search_vector ON notes (search_vector);
