-- Refresh tokens table for JWT token rotation
-- Supports refresh token rotation and revocation for secure session management
-- Compatible with both PostgreSQL and H2 (for testing)
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,  -- SHA-256 hash of the refresh token
    parent_token_hash CHAR(64),  -- Hash of the previous token in rotation chain (for theft detection)
    expires_at BIGINT NOT NULL,  -- Unix timestamp when token expires (milliseconds)
    created_at BIGINT DEFAULT 0,
    used_at BIGINT,  -- When token was used (for rotation)
    revoked_at BIGINT,  -- When token was explicitly revoked (logout, password change, etc.)
    revoke_reason VARCHAR(50),  -- 'logout', 'password_change', 'admin_revoked', 'theft_detected'
    is_current BOOLEAN DEFAULT TRUE,  -- Whether this is the active token for the user
    CONSTRAINT idx_refresh_tokens_token_hash UNIQUE (token_hash)
);

-- Indexes for common queries (H2-compatible)
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_parent ON refresh_tokens (parent_token_hash);
CREATE INDEX idx_refresh_tokens_revoked_at ON refresh_tokens (revoked_at);

-- Composite index for cleanup queries (efficient deletion of expired/revoked tokens)
CREATE INDEX idx_refresh_tokens_cleanup ON refresh_tokens (expires_at, revoked_at);
